//
// Created by igor on 16/10/2021.
//

#ifndef INCLUDE_NEUTRINO_KERNEL_SYSTEMS_VIDEO_OPENGL_VIDEO_SYSTEM_HH
#define INCLUDE_NEUTRINO_KERNEL_SYSTEMS_VIDEO_OPENGL_VIDEO_SYSTEM_HH

#endif //INCLUDE_NEUTRINO_KERNEL_SYSTEMS_VIDEO_OPENGL_VIDEO_SYSTEM_HH
