import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * The sidebar is authored by hand rather than autogenerated from the folder tree.
 *
 * Order here is pedagogical, not alphabetical: a reader coming to a game engine cold needs the
 * frame loop before scenes, and scenes before input. Autogeneration would sort those into
 * whatever the filenames happen to imply, and quietly reorder the argument whenever a page is
 * renamed. The cost is that a new page must be listed here -- which is the intended friction,
 * since an unlisted page is usually one nobody decided where to put.
 *
 * Three sections, deliberately distinct in kind:
 *   Get started -- the shortest path from nothing to a running window.
 *   Tutorial    -- one narrow path, building a single game end to end.
 *   Concepts    -- the wide explanation, entered from either of the above.
 * The exhaustive layer (every signature) is the Doxygen site, linked from the navbar.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Get started',
      collapsed: false,
      items: [
        'get-started/what-is-neutrino',
        'get-started/build',
      ],
    },
    {
      type: 'category',
      label: 'Tutorial',
      collapsed: false,
      link: {type: 'doc', id: 'tutorial/index'},
      items: [
        'tutorial/step-01-window-and-scene',
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      collapsed: false,
      link: {type: 'doc', id: 'concepts/index'},
      items: [
        'concepts/the-frame',
        'concepts/scenes',
        'concepts/input',
      ],
    },
  ],
};

export default sidebars;
