add_executable(neutrino_demo_demoscene
    main.cc
    vga_canvas.hh
    vga_canvas.cc
    gallery_scene.hh
    gallery_scene.cc
    effects/effect_base.hh
    effects/wormhole_effect.hh
    effects/wormhole_effect.cc
    effects/voxel_effect.hh
    effects/voxel_effect.cc
    effects/rotate3d_effect.hh
    effects/rotate3d_effect.cc
    effects/bobs_effect.hh
    effects/bobs_effect.cc
    effects/plasma_effect.hh
    effects/plasma_effect.cc
    effects/stars_effect.hh
    effects/stars_effect.cc
    effects/lens_effect.hh
    effects/lens_effect.cc
    effects/fire_effect.hh
    effects/fire_effect.cc
    effects/copper_effect.hh
    effects/copper_effect.cc
    effects/dypp_effect.hh
    effects/dypp_effect.cc
    effects/julia_effect.hh
    effects/julia_effect.cc
    effects/sinmap_effect.hh
    effects/sinmap_effect.cc
    effects/checkerboard3d_effect.hh
    effects/checkerboard3d_effect.cc
    effects/fadeplot_effect.hh
    effects/fadeplot_effect.cc
    effects/trans_glass3d_effect.hh
    effects/trans_glass3d_effect.cc
    effects/dots_wave_effect.hh
    effects/dots_wave_effect.cc
    effects/bounce_effect.hh
    effects/bounce_effect.cc
    effects/field_lines_effect.hh
    effects/field_lines_effect.cc
    effects/spiral_twister_effect.hh
    effects/spiral_twister_effect.cc
    effects/radar_sweep_effect.hh
    effects/radar_sweep_effect.cc
    effects/vectorballs_effect.hh
    effects/vectorballs_effect.cc
    effects/water_effect.hh
    effects/water_effect.cc
    effects/metaballs_effect.hh
    effects/metaballs_effect.cc
    effects/bump_effect.hh
    effects/bump_effect.cc
    effects/rotozoom_effect.hh
    effects/rotozoom_effect.cc
    effects/rototunnel_effect.hh
    effects/rototunnel_effect.cc
    effects/environcube_effect.hh
    effects/environcube_effect.cc
    effects/attractors_effect.hh
    effects/attractors_effect.cc
    effects/gravitational_well_effect.hh
    effects/gravitational_well_effect.cc
    effects/wavy_ribbon_effect.hh
    effects/wavy_ribbon_effect.cc
    effects/multi_sprites_effect.hh
    effects/multi_sprites_effect.cc
    effects/blinking_stars_effect.hh
    effects/blinking_stars_effect.cc
    effects/dotmorph_effect.hh
    effects/dotmorph_effect.cc
    effects/moire_effect.hh
    effects/moire_effect.cc
    effects/linedance_effect.hh
    effects/linedance_effect.cc
    effects/xor_patterns_effect.hh
    effects/xor_patterns_effect.cc
    effects/water_reflection_effect.hh
    effects/water_reflection_effect.cc
    effects/bouncing_sphere3d_effect.hh
    effects/bouncing_sphere3d_effect.cc
    effects/pixelate_effect.hh
    effects/pixelate_effect.cc
    effects/stretch_scroll_effect.hh
    effects/stretch_scroll_effect.cc
    effects/glenz_vector_effect.hh
    effects/glenz_vector_effect.cc
    effects/texture_cube_effect.hh
    effects/texture_cube_effect.cc
    effects/fractal_landscape_effect.hh
    effects/fractal_landscape_effect.cc
    effects/waving_flag_effect.hh
    effects/waving_flag_effect.cc
    effects/dot_tunnel_effect.hh
    effects/dot_tunnel_effect.cc
    effects/mesh_distort_effect.hh
    effects/mesh_distort_effect.cc
    effects/uv_deformations_effect.hh
    effects/uv_deformations_effect.cc
)

target_link_libraries(neutrino_demo_demoscene
    PRIVATE
    neutrino::neutrino
    neutrino::euler
)

target_compile_features(neutrino_demo_demoscene PRIVATE cxx_std_20)
